stages:
  - build
  - package
  - deploy

build:
  stage: build
  script:
    - cd "flash cards FE"
    - echo "VITE_API_BASE_URL=http://145.220.72.104:8080/api" > .env
    - npm install
    - npm run build
  artifacts:
    paths:
      - "flash cards FE/dist/"
    expire_in: 1 hour

package:
  stage: package
  script:
    - sudo chmod 666 /var/run/docker.sock
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - cd "flash cards FE"
    # GitLab automatically downloads the 'dist/' folder here
    - docker build --no-cache -t claracahyanintyas/flashcards-frontend:latest .
    - docker push claracahyanintyas/flashcards-frontend:latest
  only:
    - main

trigger-infra-docker:
  stage: deploy
  trigger:
    project: I545577/flash-cards-infra
    branch: main
    strategy: depend
  variables:
    TRIGGERED_BY: "frontend"
    APP_COMMIT_SHA: $CI_COMMIT_SHA
  only:
    - main