stages:
  - lint
  - deploy

lint:
  stage: lint
  script:
    - cd "flash cards FE"
    - npm ci
    - npm run lint

trigger-infra-docker:
  stage: deploy
  trigger:
    project: I545577/flash-cards-infra
    branch: main
    strategy: depend
  variables:
    TRIGGERED_BY: "frontend"
    APP_COMMIT_SHA: $CI_COMMIT_SHA
  only:
    - main