server {
    listen 80;
    server_name _;

    add_header X-Frame-Options "DENY" always;
    add_header Content-Security-Policy "default-src 'self'; connect-src 'self' http://145.220.72.104:8080; style-src 'self' 'unsafe-inline';" always;

    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
